name: Test Branch Workflow

on:
  push:
    branches:
      - 'b3'
    paths:
      - './.github/workflows/test-wf.yml'
      - 'text.txt'

jobs:
  job1:
    name: job1 success
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REF}"
  checkout:
    name: Check out
    uses: actions/checkout@v2
    needs: job1
