name: Test Branch Workflow

on:
  push:
    branches:
      - 'b3'
    paths:
      - './.github/workflows/test-wf.yml'
      - ''./test.txt'

jobs:
  job1:
    name: job1 success
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REF}"
  job2:
    name: hey mon
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "hey mon"