name: Test Branch Workflow:wq


on:
  workflow_dispatch:

jobs:
  job1:
    name: job1 success
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1 success"
  job2:
    name: job2 success
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "job2 success"