name: Test Branch Workflow

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/test-wf.yml'
      - 'text.txt'

jobs:
  job1:
    name: job1 success
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REF##*/}"
      - run: echo "${GITHUB_WORKSPACE}"

  checkout:
    name: Check out
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

  list:
    name: List files
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - run: ls -ltr
